package login;
import javax.swing.JFrame;
import java.awt.Color;
import java.sql.*;
import clases.Conexión;
import java.awt.Image;
import java.awt.Toolkit;
public class Agroregister extends javax.swing.JFrame {

    /**
     * Creates new form Agroregister
     */
    public Agroregister() {
        initComponents();
        setIconImage(getIconImage());
    }
    //Icono de JFrame
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/images/AGROP LOGO CENTRADO.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bg = new javax.swing.JPanel();
        registrar = new javax.swing.JButton();
        pacontra = new login.PanelRound();
        contraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pausu = new login.PanelRound();
        usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entrar = new login.PanelRound();
        CrearCuenta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        status = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        decoracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(230, 230, 230));
        bg.setPreferredSize(new java.awt.Dimension(1000, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        registrar.setForeground(new java.awt.Color(0, 102, 51));
        registrar.setText("¿Ya tienes una cuenta? Inicia sesión");
        registrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registrar.setBorderPainted(false);
        registrar.setContentAreaFilled(false);
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        bg.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 240, 20));

        pacontra.setBackground(new java.awt.Color(255, 255, 255));
        pacontra.setPreferredSize(new java.awt.Dimension(380, 33));
        pacontra.setRoundBottomLeft(20);
        pacontra.setRoundBottomRight(20);
        pacontra.setRoundTopLeft(20);
        pacontra.setRoundTopRight(20);

        contraseña.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        contraseña.setText("Contraseña");
        contraseña.setAutoscrolls(false);
        contraseña.setBorder(null);
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaMousePressed(evt);
            }
        });
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/candadoICON.png"))); // NOI18N

        javax.swing.GroupLayout pacontraLayout = new javax.swing.GroupLayout(pacontra);
        pacontra.setLayout(pacontraLayout);
        pacontraLayout.setHorizontalGroup(
            pacontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pacontraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pacontraLayout.setVerticalGroup(
            pacontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pacontraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(contraseña)
        );

        bg.add(pacontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 380, 40));

        pausu.setBackground(new java.awt.Color(255, 255, 255));
        pausu.setRoundBottomLeft(20);
        pausu.setRoundBottomRight(20);
        pausu.setRoundTopLeft(20);
        pausu.setRoundTopRight(20);

        usuario.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        usuario.setText("Nombre de usuario");
        usuario.setAutoscrolls(false);
        usuario.setBorder(null);
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioMousePressed(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/usuarioICON.png"))); // NOI18N

        javax.swing.GroupLayout pausuLayout = new javax.swing.GroupLayout(pausu);
        pausu.setLayout(pausuLayout);
        pausuLayout.setHorizontalGroup(
            pausuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pausuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pausuLayout.setVerticalGroup(
            pausuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pausuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(pausu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 380, 40));

        entrar.setBackground(new java.awt.Color(108, 89, 49));
        entrar.setRoundBottomLeft(20);
        entrar.setRoundBottomRight(20);
        entrar.setRoundTopLeft(20);
        entrar.setRoundTopRight(20);

        CrearCuenta.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        CrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        CrearCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearCuenta.setText("Crear cuenta");
        CrearCuenta.setAlignmentY(0.0F);
        CrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearCuentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout entrarLayout = new javax.swing.GroupLayout(entrar);
        entrar.setLayout(entrarLayout);
        entrarLayout.setHorizontalGroup(
            entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        entrarLayout.setVerticalGroup(
            entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CrearCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        bg.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 380, 35));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 51));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 380, 10));

        status.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(0, 102, 0));
        bg.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 240, 40));

        jLabel6.setBackground(new java.awt.Color(0, 102, 51));
        jLabel6.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("REGISTRARSE");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        decoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/DecoracionRegistro)=3.png"))); // NOI18N
        bg.add(decoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Agrologin b = new Agrologin();
        this.setVisible(false);
        b.setVisible(true);
    }                                         

    private void contraseñaMousePressed(java.awt.event.MouseEvent evt) {                                        
        if(contraseña.getText().equals("Contraseña")){
            contraseña.setText("");
        }
        if(usuario.getText().isEmpty()){
            usuario.setText("Nombre de usuario");
        }
    }                                       

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void usuarioMousePressed(java.awt.event.MouseEvent evt) {                                     
        if(usuario.getText().equals("Nombre de usuario")){
            usuario.setText("");
        }
        if(contraseña.getText().isEmpty()){
            contraseña.setText("Contraseña");
        }
    }                                    

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void CrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {                                         
        entrar.setBackground(new Color(61,53,37));
    }                                        

    private void CrearCuentaMouseExited(java.awt.event.MouseEvent evt) {                                        
        entrar.setBackground(new Color(108,89,49));
    }                                       

    private void CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {                                         
        //Compruebo que los textfield tengan algo adentro
        if(!usuario.getText().equals("") && !contraseña.getText().equals("")){
            //Es necesario hacer el try-catch para la conexion
            try{
                //conexion a la base de datos
                Connection cn = Conexión.conectar();

                //instruccion a la base de datos (le voy a mandar los valores del usuario)
                PreparedStatement pst = cn.prepareStatement("insert into usuario values (?, ?, ?)");

                //aqui le digo a que columnas van dichos valores
                pst.setString(1, "0");
                pst.setString(2, usuario.getText().trim()); //El trim es para que no me coja espacios en blanco
                pst.setString(3, contraseña.getText().trim());

                //le digo a java y a la base de datos que ejecute lo anterior
                pst.executeUpdate();

                //limpio los txt
                usuario.setText("");
                contraseña.setText("");
                decoracion.setText("");
                status.setText("Cuenta creada exitosamente");

            }
            catch (Exception e){
            }
        }
        else{
        }
        //---------
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agroregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel CrearCuenta;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel decoracion;
    private login.PanelRound entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private login.PanelRound pacontra;
    private login.PanelRound pausu;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel status;
    private javax.swing.JTextField usuario;
    // End of variables declaration                   
}
