package login;

//sebas
import java.sql.*;

import javax.swing.JFrame;
import java.awt.Color;
public class Agroregister extends javax.swing.JFrame {

    /**
     * Creates new form Agroregister
     */
    public Agroregister() {
        initComponents();
        
        //sebas
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bg = new javax.swing.JPanel();
        minim = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        pacontra = new login.PanelRound();
        txt_contraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pausu = new login.PanelRound();
        txt_usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entrar = new login.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        cerrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        decoracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(20, 20, 20));
        bg.setPreferredSize(new java.awt.Dimension(1000, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minim.setBackground(new java.awt.Color(108, 89, 49));

        jLabel4.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("—");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimLayout = new javax.swing.GroupLayout(minim);
        minim.setLayout(minimLayout);
        minimLayout.setHorizontalGroup(
            minimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        minimLayout.setVerticalGroup(
            minimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(minim, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, 30));

        registrar.setFont(new java.awt.Font("Gotham", 0, 12)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("¿Ya tienes una cuenta? Inicia sesión");
        registrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registrar.setBorderPainted(false);
        registrar.setContentAreaFilled(false);
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        bg.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 240, 20));

        pacontra.setBackground(new java.awt.Color(41, 41, 41));
        pacontra.setPreferredSize(new java.awt.Dimension(380, 33));
        pacontra.setRoundBottomLeft(20);
        pacontra.setRoundBottomRight(20);
        pacontra.setRoundTopLeft(20);
        pacontra.setRoundTopRight(20);

        txt_contraseña.setBackground(new java.awt.Color(41, 41, 41));
        txt_contraseña.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_contraseña.setText("Contraseña");
        txt_contraseña.setAutoscrolls(false);
        txt_contraseña.setBorder(null);
        txt_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contraseñaMousePressed(evt);
            }
        });
        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/candadoICON.png"))); // NOI18N

        javax.swing.GroupLayout pacontraLayout = new javax.swing.GroupLayout(pacontra);
        pacontra.setLayout(pacontraLayout);
        pacontraLayout.setHorizontalGroup(
            pacontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pacontraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pacontraLayout.setVerticalGroup(
            pacontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pacontraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(txt_contraseña)
        );

        bg.add(pacontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 380, 40));

        pausu.setBackground(new java.awt.Color(41, 41, 41));
        pausu.setRoundBottomLeft(20);
        pausu.setRoundBottomRight(20);
        pausu.setRoundTopLeft(20);
        pausu.setRoundTopRight(20);

        txt_usuario.setBackground(new java.awt.Color(41, 41, 41));
        txt_usuario.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setText("Nombre de usuario");
        txt_usuario.setAutoscrolls(false);
        txt_usuario.setBorder(null);
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/usuarioICON.png"))); // NOI18N

        javax.swing.GroupLayout pausuLayout = new javax.swing.GroupLayout(pausu);
        pausu.setLayout(pausuLayout);
        pausuLayout.setHorizontalGroup(
            pausuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pausuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pausuLayout.setVerticalGroup(
            pausuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pausuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(pausu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 380, 40));

        entrar.setBackground(new java.awt.Color(108, 89, 49));
        entrar.setRoundBottomLeft(20);
        entrar.setRoundBottomRight(20);
        entrar.setRoundTopLeft(20);
        entrar.setRoundTopRight(20);

        jLabel2.setFont(new java.awt.Font("Gotham", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear cuenta");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout entrarLayout = new javax.swing.GroupLayout(entrar);
        entrar.setLayout(entrarLayout);
        entrarLayout.setHorizontalGroup(
            entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        entrarLayout.setVerticalGroup(
            entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        bg.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 380, 35));

        cerrar.setBackground(new java.awt.Color(108, 89, 49));

        jLabel3.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarLayout = new javax.swing.GroupLayout(cerrar);
        cerrar.setLayout(cerrarLayout);
        cerrarLayout.setHorizontalGroup(
            cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cerrarLayout.setVerticalGroup(
            cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REGISTRARSE");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        label_status.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        label_status.setForeground(new java.awt.Color(255, 255, 255));
        bg.add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 180, 30));

        decoracion.setForeground(new java.awt.Color(255, 255, 255));
        decoracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/DecoracionRegistro)=3.png"))); // NOI18N
        decoracion.setText("jLabel1");
        bg.add(decoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
        this.setState(JFrame.ICONIFIED);
    }                                    

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {                                     
        minim.setBackground(Color.red);
    }                                    

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {                                    
        minim.setBackground(new Color(108,89,49));
    }                                   

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        System.exit(0);
    }                                    

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        cerrar.setBackground(Color.red);
    }                                    

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {                                    
        cerrar.setBackground(new Color(108,89,49));
    }                                   

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Agrologin b = new Agrologin();
        this.setVisible(false);
        b.setVisible(true);
    }                                         

    private void txt_contraseñaMousePressed(java.awt.event.MouseEvent evt) {                                            
        if(txt_contraseña.getText().equals("Contraseña")){
            txt_contraseña.setText("");
        }
        if(txt_usuario.getText().isEmpty()){
            txt_usuario.setText("Nombre de usuario");
        }
    }                                           

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {                                         
        if(txt_usuario.getText().equals("Nombre de usuario")){
            txt_usuario.setText("");
        }
        if(txt_contraseña.getText().isEmpty()){
            txt_contraseña.setText("Contraseña");
        }
    }                                        

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {                                     
        entrar.setBackground(new Color(61,53,37));
    }                                    

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {                                    
        entrar.setBackground(new Color(108,89,49));
    }                                   

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        
        //sebas
        try{
            //conexion a la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/agrop", "root", "1846583467");
            
            //instruccion a la base de datos (le voy a mandar los valores del usuario)
            PreparedStatement pst = cn.prepareStatement("insert into usuario values (?, ?, ?)");
            
            //aqui le digo a que columnas van dichos valores
            pst.setString(1, "0");
            //txt_usuario es como se llama el jtextfield de donde vamos a sacar este dato
            pst.setString(2, txt_usuario.getText().trim());
            pst.setString(3, txt_contraseña.getText().trim());
            
            //le digo a java y a la base de datos que ejecute lo anterior
            pst.executeUpdate();
            
            //limpio los txt
            txt_usuario.setText("");
            txt_contraseña.setText("");
            
            //modifico el jlabel para que me diga que ya se registro el usuario
            label_status.setText("Registro exitoso.");

    
        }catch (Exception e){
            
        }
        
        
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agroregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agroregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel bg;
    private javax.swing.JPanel cerrar;
    private javax.swing.JLabel decoracion;
    private login.PanelRound entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_status;
    private javax.swing.JPanel minim;
    private login.PanelRound pacontra;
    private login.PanelRound pausu;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration                   
}
