package login;
import javax.swing.JFrame;
import java.awt.Color;
public class Agrosuelos extends javax.swing.JFrame {

    /**
     * Creates new form Agrosuelos
     */
    public Agrosuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        KKKKK = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        minim = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cerrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        agregarpanel = new login.PanelRound();
        agregarjlabel = new javax.swing.JLabel();
        borrarpanel = new login.PanelRound();
        borrarjlabel = new javax.swing.JLabel();
        panelmenus = new login.PanelRound();
        panelRound1 = new login.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        panelRound9 = new login.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        ingresarpanel = new login.PanelRound();
        ingresarjlabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minim.setBackground(new java.awt.Color(108, 89, 49));

        jLabel4.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("—");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimLayout = new javax.swing.GroupLayout(minim);
        minim.setLayout(minimLayout);
        minimLayout.setHorizontalGroup(
            minimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        minimLayout.setVerticalGroup(
            minimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(minim, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 0, -1, 30));

        cerrar.setBackground(new java.awt.Color(108, 89, 49));

        jLabel3.setFont(new java.awt.Font("Gotham", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarLayout = new javax.swing.GroupLayout(cerrar);
        cerrar.setLayout(cerrarLayout);
        cerrarLayout.setHorizontalGroup(
            cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cerrarLayout.setVerticalGroup(
            cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 0, 30, 30));

        agregarpanel.setBackground(new java.awt.Color(108, 89, 49));
        agregarpanel.setRoundBottomLeft(10);
        agregarpanel.setRoundBottomRight(10);
        agregarpanel.setRoundTopLeft(10);
        agregarpanel.setRoundTopRight(10);

        agregarjlabel.setFont(new java.awt.Font("Gotham", 1, 22)); // NOI18N
        agregarjlabel.setForeground(new java.awt.Color(255, 255, 255));
        agregarjlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarjlabel.setText("AGREGAR");
        agregarjlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarjlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarjlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarjlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarjlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout agregarpanelLayout = new javax.swing.GroupLayout(agregarpanel);
        agregarpanel.setLayout(agregarpanelLayout);
        agregarpanelLayout.setHorizontalGroup(
            agregarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregarjlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        agregarpanelLayout.setVerticalGroup(
            agregarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregarjlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(agregarpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 210, 40));

        borrarpanel.setBackground(new java.awt.Color(108, 89, 49));
        borrarpanel.setRoundBottomLeft(10);
        borrarpanel.setRoundBottomRight(10);
        borrarpanel.setRoundTopLeft(10);
        borrarpanel.setRoundTopRight(10);

        borrarjlabel.setFont(new java.awt.Font("Gotham", 1, 22)); // NOI18N
        borrarjlabel.setForeground(new java.awt.Color(255, 255, 255));
        borrarjlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrarjlabel.setText("BORRAR");
        borrarjlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarjlabel.setRequestFocusEnabled(false);
        borrarjlabel.setVerifyInputWhenFocusTarget(false);
        borrarjlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarjlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarjlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout borrarpanelLayout = new javax.swing.GroupLayout(borrarpanel);
        borrarpanel.setLayout(borrarpanelLayout);
        borrarpanelLayout.setHorizontalGroup(
            borrarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarjlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        borrarpanelLayout.setVerticalGroup(
            borrarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarjlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(borrarpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 210, 40));

        panelmenus.setBackground(new java.awt.Color(41, 41, 41));
        panelmenus.setRoundBottomLeft(10);
        panelmenus.setRoundBottomRight(10);
        panelmenus.setRoundTopLeft(10);
        panelmenus.setRoundTopRight(10);

        panelRound1.setBackground(new java.awt.Color(60, 60, 60));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        jLabel2.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lote 1");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound9.setBackground(new java.awt.Color(60, 60, 60));
        panelRound9.setRoundBottomLeft(10);
        panelRound9.setRoundBottomRight(10);
        panelRound9.setRoundTopLeft(10);
        panelRound9.setRoundTopRight(10);

        jLabel15.setFont(new java.awt.Font("Gotham", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lote 2");

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelmenusLayout = new javax.swing.GroupLayout(panelmenus);
        panelmenus.setLayout(panelmenusLayout);
        panelmenusLayout.setHorizontalGroup(
            panelmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenusLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelmenusLayout.setVerticalGroup(
            panelmenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jPanel1.add(panelmenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 430, 320));

        ingresarpanel.setBackground(new java.awt.Color(108, 89, 49));
        ingresarpanel.setRoundBottomLeft(10);
        ingresarpanel.setRoundBottomRight(10);
        ingresarpanel.setRoundTopLeft(10);
        ingresarpanel.setRoundTopRight(10);

        ingresarjlabel.setFont(new java.awt.Font("Gotham", 1, 22)); // NOI18N
        ingresarjlabel.setForeground(new java.awt.Color(255, 255, 255));
        ingresarjlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresarjlabel.setText("INGRESAR");
        ingresarjlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresarjlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ingresarjlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarjlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarjlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarjlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ingresarpanelLayout = new javax.swing.GroupLayout(ingresarpanel);
        ingresarpanel.setLayout(ingresarpanelLayout);
        ingresarpanelLayout.setHorizontalGroup(
            ingresarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarjlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        ingresarpanelLayout.setVerticalGroup(
            ingresarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresarjlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(ingresarpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 430, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/circulo 130130.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -40, 210, 150));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/circulo 5050.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/circulo 5050.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/circulo 5050.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {                                     
        this.setState(JFrame.ICONIFIED);
    }                                    

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {                                     
        minim.setBackground(Color.red);
    }                                    

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {                                    
        minim.setBackground(new Color(108,89,49));
    }                                   

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        System.exit(0);
    }                                    

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        cerrar.setBackground(Color.red);
    }                                    

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {                                    
        cerrar.setBackground(new Color(108,89,49));
    }                                   

    private void agregarjlabelMouseEntered(java.awt.event.MouseEvent evt) {                                           
        agregarpanel.setBackground(new Color(61,53,37));
    }                                          

    private void agregarjlabelMouseExited(java.awt.event.MouseEvent evt) {                                          
        agregarpanel.setBackground(new Color(108,89,49));
    }                                         

    private void borrarjlabelMouseEntered(java.awt.event.MouseEvent evt) {                                          
        borrarpanel.setBackground(new Color(61,53,37));
    }                                         

    private void borrarjlabelMouseExited(java.awt.event.MouseEvent evt) {                                         
        borrarpanel.setBackground(new Color(108,89,49));
    }                                        

    private void ingresarjlabelMouseEntered(java.awt.event.MouseEvent evt) {                                            
        ingresarpanel.setBackground(new Color(61,53,37));
    }                                           

    private void ingresarjlabelMouseExited(java.awt.event.MouseEvent evt) {                                           
        ingresarpanel.setBackground(new Color(108,89,49));
    }                                          

    private void ingresarjlabelMouseClicked(java.awt.event.MouseEvent evt) {                                            
        Agrodatos a = new Agrodatos();
        this.setVisible(false);
        a.setVisible(true);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agrosuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agrosuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agrosuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agrosuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agrosuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup KKKKK;
    private javax.swing.JLabel agregarjlabel;
    private login.PanelRound agregarpanel;
    private javax.swing.JLabel borrarjlabel;
    private login.PanelRound borrarpanel;
    private javax.swing.JPanel cerrar;
    private javax.swing.JLabel ingresarjlabel;
    private login.PanelRound ingresarpanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel minim;
    private login.PanelRound panelRound1;
    private login.PanelRound panelRound4;
    private login.PanelRound panelRound8;
    private login.PanelRound panelRound9;
    private login.PanelRound panelmenus;
    // End of variables declaration                   
}
